// Code generated by protoc-gen-go.
// source: color-generator.proto
// DO NOT EDIT!

/*
Package colorgen is a generated protocol buffer package.

It is generated from these files:
	color-generator.proto

It has these top-level messages:
	Empty
	Color
*/
package colorgen

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Color struct {
	Hex string `protobuf:"bytes,1,opt,name=hex" json:"hex,omitempty"`
}

func (m *Color) Reset()                    { *m = Color{} }
func (m *Color) String() string            { return proto.CompactTextString(m) }
func (*Color) ProtoMessage()               {}
func (*Color) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Color) GetHex() string {
	if m != nil {
		return m.Hex
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "colorgen.Empty")
	proto.RegisterType((*Color)(nil), "colorgen.Color")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ColorGeneratorService service

type ColorGeneratorServiceClient interface {
	GetColor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Color, error)
}

type colorGeneratorServiceClient struct {
	cc *grpc.ClientConn
}

func NewColorGeneratorServiceClient(cc *grpc.ClientConn) ColorGeneratorServiceClient {
	return &colorGeneratorServiceClient{cc}
}

func (c *colorGeneratorServiceClient) GetColor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Color, error) {
	out := new(Color)
	err := grpc.Invoke(ctx, "/colorgen.ColorGeneratorService/GetColor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ColorGeneratorService service

type ColorGeneratorServiceServer interface {
	GetColor(context.Context, *Empty) (*Color, error)
}

func RegisterColorGeneratorServiceServer(s *grpc.Server, srv ColorGeneratorServiceServer) {
	s.RegisterService(&_ColorGeneratorService_serviceDesc, srv)
}

func _ColorGeneratorService_GetColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColorGeneratorServiceServer).GetColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colorgen.ColorGeneratorService/GetColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColorGeneratorServiceServer).GetColor(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ColorGeneratorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "colorgen.ColorGeneratorService",
	HandlerType: (*ColorGeneratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetColor",
			Handler:    _ColorGeneratorService_GetColor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "color-generator.proto",
}

func init() { proto.RegisterFile("color-generator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xce, 0xcf, 0xc9,
	0x2f, 0xd2, 0x4d, 0x4f, 0xcd, 0x4b, 0x2d, 0x4a, 0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x00, 0x0b, 0xa7, 0xa7, 0xe6, 0x29, 0xb1, 0x73, 0xb1, 0xba, 0xe6, 0x16, 0x94,
	0x54, 0x2a, 0x49, 0x72, 0xb1, 0x3a, 0x83, 0x04, 0x85, 0x04, 0xb8, 0x98, 0x33, 0x52, 0x2b, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x23, 0x77, 0x2e, 0x51, 0xb0, 0x94, 0x3b, 0xcc,
	0x94, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x3d, 0x2e, 0x0e, 0xf7, 0xd4, 0x12, 0x88,
	0x36, 0x7e, 0x3d, 0x98, 0x99, 0x7a, 0x60, 0x03, 0xa5, 0x90, 0x04, 0xc0, 0x2a, 0x94, 0x18, 0x92,
	0xd8, 0xc0, 0xb6, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x74, 0xad, 0xd7, 0x96, 0x00,
	0x00, 0x00,
}
