apiVersion: v1
kind: Service
metadata:
  name: color-requestor
  labels:
    name: color-requestor
spec:
  type: LoadBalancer
  ports:
  - name: socket-server
    port: 8080
    targetPort: 8080
  selector:
    name: color-requestor