// Code generated by protoc-gen-go.
// source: charlotte/common/traits/profile/v1/itrait.proto
// DO NOT EDIT!

/*
Package charlotte_common_traits_profile_v1 is a generated protocol buffer package.

It is generated from these files:
	charlotte/common/traits/profile/v1/itrait.proto

It has these top-level messages:
	ITrait
*/
package charlotte_common_traits_profile_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProfileTraitType int32

const (
	ProfileTraitType_FILLER ProfileTraitType = 0
)

var ProfileTraitType_name = map[int32]string{
	0: "FILLER",
}
var ProfileTraitType_value = map[string]int32{
	"FILLER": 0,
}

func (x ProfileTraitType) String() string {
	return proto.EnumName(ProfileTraitType_name, int32(x))
}
func (ProfileTraitType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ITrait struct {
	Type    ProfileTraitType `protobuf:"varint,1,opt,name=type,enum=charlotte.common.traits.profile.v1.ProfileTraitType" json:"type,omitempty"`
	Payload []byte           `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ITrait) Reset()                    { *m = ITrait{} }
func (m *ITrait) String() string            { return proto.CompactTextString(m) }
func (*ITrait) ProtoMessage()               {}
func (*ITrait) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ITrait) GetType() ProfileTraitType {
	if m != nil {
		return m.Type
	}
	return ProfileTraitType_FILLER
}

func (m *ITrait) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*ITrait)(nil), "charlotte.common.traits.profile.v1.ITrait")
	proto.RegisterEnum("charlotte.common.traits.profile.v1.ProfileTraitType", ProfileTraitType_name, ProfileTraitType_value)
}

func init() { proto.RegisterFile("charlotte/common/traits/profile/v1/itrait.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4f, 0xce, 0x48, 0x2c,
	0xca, 0xc9, 0x2f, 0x29, 0x49, 0xd5, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x2f, 0x29, 0x4a,
	0xcc, 0x2c, 0x29, 0xd6, 0x2f, 0x28, 0xca, 0x4f, 0xcb, 0xcc, 0x49, 0xd5, 0x2f, 0x33, 0xd4, 0xcf,
	0x04, 0x0b, 0xe9, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x29, 0xc1, 0x35, 0xe8, 0x41, 0x34, 0xe8,
	0x41, 0x34, 0xe8, 0x41, 0x35, 0xe8, 0x95, 0x19, 0x2a, 0xe5, 0x70, 0xb1, 0x79, 0x86, 0x80, 0x44,
	0x85, 0x3c, 0xb8, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x4c,
	0xf4, 0x08, 0x6b, 0xd6, 0x0b, 0x80, 0x30, 0xc1, 0xfa, 0x43, 0x2a, 0x0b, 0x52, 0x83, 0xc0, 0x26,
	0x08, 0x49, 0x70, 0xb1, 0x17, 0x24, 0x56, 0xe6, 0xe4, 0x27, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x6a,
	0xf0, 0x04, 0xc1, 0xb8, 0x5a, 0x72, 0x5c, 0x02, 0xe8, 0x7a, 0x84, 0xb8, 0xb8, 0xd8, 0xdc, 0x3c,
	0x7d, 0x7c, 0x5c, 0x83, 0x04, 0x18, 0x92, 0xd8, 0xc0, 0x0e, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0x83, 0xed, 0xac, 0xeb, 0x00, 0x00, 0x00,
}
