// Code generated by protoc-gen-go.
// source: charlotte/common/traits/person/v1/itrait.proto
// DO NOT EDIT!

/*
Package charlotte_common_traits_person_v1 is a generated protocol buffer package.

It is generated from these files:
	charlotte/common/traits/person/v1/itrait.proto

It has these top-level messages:
	ITrait
*/
package charlotte_common_traits_person_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PersonTraitType int32

const (
	PersonTraitType_FILLER PersonTraitType = 0
)

var PersonTraitType_name = map[int32]string{
	0: "FILLER",
}
var PersonTraitType_value = map[string]int32{
	"FILLER": 0,
}

func (x PersonTraitType) String() string {
	return proto.EnumName(PersonTraitType_name, int32(x))
}
func (PersonTraitType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ITrait struct {
	Type    PersonTraitType `protobuf:"varint,1,opt,name=type,enum=charlotte.common.traits.person.v1.PersonTraitType" json:"type,omitempty"`
	Payload []byte          `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ITrait) Reset()                    { *m = ITrait{} }
func (m *ITrait) String() string            { return proto.CompactTextString(m) }
func (*ITrait) ProtoMessage()               {}
func (*ITrait) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ITrait) GetType() PersonTraitType {
	if m != nil {
		return m.Type
	}
	return PersonTraitType_FILLER
}

func (m *ITrait) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*ITrait)(nil), "charlotte.common.traits.person.v1.ITrait")
	proto.RegisterEnum("charlotte.common.traits.person.v1.PersonTraitType", PersonTraitType_name, PersonTraitType_value)
}

func init() { proto.RegisterFile("charlotte/common/traits/person/v1/itrait.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4b, 0xce, 0x48, 0x2c,
	0xca, 0xc9, 0x2f, 0x29, 0x49, 0xd5, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x2f, 0x29, 0x4a,
	0xcc, 0x2c, 0x29, 0xd6, 0x2f, 0x48, 0x2d, 0x2a, 0xce, 0xcf, 0xd3, 0x2f, 0x33, 0xd4, 0xcf, 0x04,
	0x8b, 0xe8, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x29, 0xc2, 0xd5, 0xeb, 0x41, 0xd4, 0xeb, 0x41,
	0xd4, 0xeb, 0x41, 0xd4, 0xeb, 0x95, 0x19, 0x2a, 0x65, 0x71, 0xb1, 0x79, 0x86, 0x80, 0x04, 0x85,
	0xdc, 0xb8, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x8c, 0xf4,
	0x08, 0xea, 0xd5, 0x0b, 0x00, 0xb3, 0xc0, 0xba, 0x43, 0x2a, 0x0b, 0x52, 0x83, 0xc0, 0xfa, 0x85,
	0x24, 0xb8, 0xd8, 0x0b, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78,
	0x82, 0x60, 0x5c, 0x2d, 0x59, 0x2e, 0x7e, 0x34, 0x2d, 0x42, 0x5c, 0x5c, 0x6c, 0x6e, 0x9e, 0x3e,
	0x3e, 0xae, 0x41, 0x02, 0x0c, 0x49, 0x6c, 0x60, 0x47, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x41, 0x4b, 0xb3, 0xed, 0xe6, 0x00, 0x00, 0x00,
}
